# Generated by Django 3.1.6 on 2021-04-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_auto_20210414_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_app.address'),
        ),
        migrations.AlterField(
            model_name='potentialsales',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.car'),
        ),
    ]
