# Generated by Django 3.1.6 on 2021-04-28 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_auto_20210428_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potentialsales',
            name='car_id',
        ),
        migrations.AddField(
            model_name='potentialsales',
            name='inv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potentialsales',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.customer'),
        ),
    ]
